
   -- create table DOCUMENT
    DROP TABLE IF EXISTS DOCUMENT;
    CREATE TABLE DOCUMENT (
      ID BIGINT AUTO_INCREMENT PRIMARY KEY,
      NAME VARCHAR(255),
      CONTENT TEXT,
      FILE_TYPE VARCHAR(10),
      CREATED_BY VARCHAR(255),
      CREATED_AT TIMESTAMP,
      UPDATED_AT TIMESTAMP
    );

    -- create table DOCUMENT_PERMISSION
    DROP TABLE IF EXISTS DOCUMENT_PERMISSION;
    CREATE TABLE DOCUMENT_PERMISSION (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     DOCUMENT_ID BIGINT,
     USERNAME VARCHAR(255),
     PERMISSION_TYPE VARCHAR(10),
     CREATED_AT TIMESTAMP,
     FOREIGN KEY (document_id) REFERENCES document(id)
    );

-- Insert sample documents
   INSERT INTO DOCUMENT (ID, NAME, CONTENT, FILE_TYPE, CREATED_BY, CREATED_AT, UPDATED_AT) VALUES
       (90000, 'Sample Document', 'This is a test document for permission testing.', 'PDF', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (20000, 'Project Plan', 'This document outline.', 'PDF', 'manager1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert permissions for document ID 1
   INSERT INTO DOCUMENT_PERMISSION (DOCUMENT_ID, USERNAME, PERMISSION_TYPE, CREATED_AT) VALUES
        (90000, 'user2', 'READ', CURRENT_TIMESTAMP),
        (90000, 'user3', 'WRITE', CURRENT_TIMESTAMP);

-- Insert permissions for document ID 2
   INSERT INTO DOCUMENT_PERMISSION (DOCUMENT_ID, USERNAME, PERMISSION_TYPE, CREATED_AT) VALUES
        (20000, 'user2', 'READ', CURRENT_TIMESTAMP),
        (20000, 'user4', 'WRITE', CURRENT_TIMESTAMP),
        (20000, 'admin', 'DELETE', CURRENT_TIMESTAMP);